# -*- mode: python ; coding: utf-8 -*-
# Build: pyinstaller KPI_assistant.spec

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config.ini',              '.'),
        ('version.json',            '.'),
        ('app/skills_matrix',       'app/skills_matrix'),
        ('_token.txt',              '.'),
    ],
    hiddenimports=[
        'app',
        'app.config',
        'app.constants',
        'app.processed_log',
        'app.processor',
        'app.watcher',
        'app.tray',
        'app.ui',
        'app.ui.app',
        'app.ui.dashboard',
        'app.ui.config_tab',
        'app.ui.widgets',
        'app.ui.context_dialog',
        'app.ai_provider',
        'app.secrets',
        'app.ollama_setup',
        'app.kpa_context',
        'app.worker_deploy',
        'app.ui.worker_wizard',
        'app.worker_version',
        'anthropic',
        'openai',
        'app.ui.capture_overlay',
        'app.ui.update_dialog',
        'app.screenshot',
        'pynput',
        'pynput.keyboard',
        'pynput.keyboard._win32',
        'mss',
        'mss.tools',
        'customtkinter',
        'darkdetect',
        'google.genai',
        'watchdog.observers',
        'watchdog.observers.polling',
        'watchdog.events',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'packaging',
        'packaging.version',
        'app.worker_deploy',
        'app.ui.worker_wizard'

    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='KPI_Assistant',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon='icon.ico',
)
